Cambios en funcion de crear nueva marca tipo pausa para permitir editar
MISO4101-202010/Proyecto-Backend pull request #15
Opened 2020-04-23 00:29 UTC by devergel

2020-04-23 00:36 UTC, juanalvarez123 requested changes
Revisión hecha, comentarios pendientes

2020-04-23 00:36 UTC, juanalvarez123 commented on activities/views.py
>      def post(self, request, *args, **kwargs):
¿Por que se está modificando el método POST? ... Para hacer una modificación de un recurso se debe usar un método PATCH o PUT

2020-04-23 01:31 UTC, devergel commented on activities/views.py
>      def post(self, request, *args, **kwargs):
Gracias por el comentario , es correcto la firma del método se debe cambiar a PUT de acuerdo a la modificación ya que se crea o se actualiza el objeto unificando así estas 2 operaciones, ya se realizo este refactor

2020-04-23 01:34 UTC, larry852 commented on activities/views.py
>      def post(self, request, *args, **kwargs):
Esto afecta el llamado actual que se tiene en el front ? el cual es post sobre este recurso ?

2020-04-23 01:42 UTC, devergel commented on activities/views.py
>      def post(self, request, *args, **kwargs):
Hola Larry , si efectivamente afecta la invocación desde el front el cambio también fue aplicado allí , ya que se consume desde la capa service el cambio no afecta ningun otro punto , la función PUT cubre las dos funcionalidades creación y modificación así que no es necesario el modo POST

2020-04-23 01:47 UTC, larry852 requested changes

2020-04-23 01:47 UTC, larry852 commented on activities/views.py
> +class PausaDetail(RetrieveUpdateAPIView):
RetrieveUpdateAPIView, es para uso de lectura o actualizacion(parcial o completa) de un objecto del model. 
https://www.django-rest-framework.org/api-guide/generic-views/#retrieveupdateapiview

2020-04-23 01:47 UTC, larry852 commented on activities/views.py
> +    def put(self, request, *args, **kwargs):
put (actualizacion completa) o patch (actaulizacion parcial) solo deberian encargarse de la actualizacion.

2020-04-23 01:47 UTC, larry852 commented on activities/views.py
> +            # pregunta = pregunta1[0].preguntaSeleccionMultiple
This block of commented-out lines of code should be removed.

2020-04-23 20:28 UTC, mateodevia approved these changes

2020-04-26 15:28 UTC, larry852 approved these changes

2020-04-26 15:52 UTC, juanalvarez123 approved these changes
De acuerdo a lo conversado, creemos que las funcionalidades de creación y modificación de un recurso deberían ir separadas en métodos POST y PUT/PATCH respectivamente, sin embargo, esto quedará como una mejora para más adelante

2020-04-26 19:12 UTC, merged