Retorno de retroalimentación para las preguntas y de todo el contenid…
MISO4101-202010/Proyecto-Backend pull request #24
Opened 2020-04-29 02:16 UTC by Draka

…o interactivo

2020-04-29 03:51 UTC, jfmatheusg approved these changes

2020-04-29 13:39 UTC, juanalvarez123 commented on activities/serializers.py
> +    # actividad = ActividadPreguntaSerializer(many=True)
No es buena práctica subir código comentado

2020-04-29 13:40 UTC, juanalvarez123 commented on activities/views.py
> +        # interactive_content = ContenidoInteractivo.objects.get(id=id)
Borrar esta línea comentada

2020-04-29 13:40 UTC, juanalvarez123 approved these changes

2020-04-29 13:43 UTC, juanalvarez123 requested changes
Por favor revisar el análisis de Codacy que está reportando fallos

2020-05-01 01:11 UTC, wavaleros approved these changes

2020-05-01 03:32 UTC, merged